<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\src\.imports\Template.props"/>
  <Import Project="..\..\src\.imports\Template.targets"/>

  <PropertyGroup>
    <UsingSerilog>true</UsingSerilog>
  </PropertyGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <ApplicationIcon>App.ico</ApplicationIcon>
    <SuppressTrimAnalysisWarnings>true</SuppressTrimAnalysisWarnings>
    <RootNamespace>Gearbox.Shell</RootNamespace>
    <AssemblyName>Gearbox</AssemblyName>
  </PropertyGroup>

  <PropertyGroup>
    <Product>Gearbox</Product>
    <Description>Gearbox Browser Launcher</Description>
    <Company>Enner Pérez</Company>
    <Copyright>Copyright © $([System.DateTime]::Now.Year)</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/ennerperez/gearbox/gearbox.git</PackageProjectUrl>
    <RepositoryUrl>https://github.com/gearbox/gearbox.git</RepositoryUrl>
    <RepositoryType>Public</RepositoryType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release' and '$(DisableAOT)' != 'true'">
    <PublishAot>true</PublishAot>
    <PublishTrimmed>true</PublishTrimmed>
    <TrimMode>link</TrimMode>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="App.ico"/>
    <AvaloniaResource Include="Assets\**"/>
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="..\..\res\icons\gearbox.icns">
      <Link>Assets/gearbox.icns</Link>
      <DependentUpon>gearbox.svg</DependentUpon>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </AvaloniaResource>
    <AvaloniaResource Include="..\..\res\icons\gearbox.ico">
      <Link>Assets/gearbox.ico</Link>
      <DependentUpon>gearbox.svg</DependentUpon>
    </AvaloniaResource>
    <AvaloniaResource Include="..\..\res\icons\gearbox.png">
      <Link>Assets/gearbox.png</Link>
      <DependentUpon>gearbox.svg</DependentUpon>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </AvaloniaResource>
    <AvaloniaResource Include="..\..\res\icons\gearbox.svg">
      <Link>Assets/gearbox.svg</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </AvaloniaResource>
    <AvaloniaResource Include="..\..\res\natives\linux\Gearbox.Desktop">
      <Link>Natives/Linux/Gearbox.Desktop</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </AvaloniaResource>
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\Core\Config.ini">
      <Link>Config.ini</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="..\Core\Config.*.ini">
      <DependentUpon>Config.ini</DependentUpon>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DesktopNotifications.Avalonia"/>
    <PackageReference Include="Microsoft.Extensions.Configuration"/>
    <PackageReference Include="Microsoft.Extensions.Configuration.Json"/>
    <PackageReference Include="Microsoft.Extensions.Configuration.CommandLine"/>
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables"/>
    <PackageReference Include="Microsoft.Extensions.Configuration.Ini"/>
    <PackageReference Include="Avalonia"/>
    <PackageReference Include="Avalonia.Desktop"/>
    <PackageReference Include="Avalonia.Fonts.Inter"/>
    <PackageReference Include="Avalonia.Themes.Fluent"/>
    <!--Condition below is needed to remove AvaloniaUI.DiagnosticsSupport package from build output in Release configuration.-->
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Condition="'$(Configuration)' == 'Debug'">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection"/>
    <PackageReference Include="CommunityToolkit.Mvvm"/>
    <PackageReference Include="ShimSkiaSharp"/>
    <PackageReference Include="Skia.Controls.Avalonia"/>
    <PackageReference Include="SkiaSharp"/>
    <PackageReference Include="SkiaSharp.HarfBuzz"/>
    <PackageReference Include="SkiaSharp.NativeAssets.Linux"/>
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies"/>
    <PackageReference Include="SkiaSharp.NativeAssets.macOS"/>
    <PackageReference Include="SkiaSharp.NativeAssets.WebAssembly"/>
    <PackageReference Include="SkiaSharp.NativeAssets.Win32"/>
    <PackageReference Include="Svg.Controls.Skia.Avalonia"/>
  </ItemGroup>

  <ItemGroup>
    <TrimmerRootAssembly Include="Avalonia.Themes.Fluent"/>
  </ItemGroup>

  <ItemGroup Condition="$([MSBuild]::IsOSPlatform('OSX'))">
    <LinkerArg Include="-mmacosx-version-min=11.0" Condition="'$(Configuration)' == 'Release'"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\Core.csproj"/>
  </ItemGroup>

</Project>
