<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\src\.imports\Template.props" />
  <Import Project="..\..\src\.imports\Template.targets" />

  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>Gearbox.Core</RootNamespace>
    <AssemblyName>Gearbox.Core</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LiteDB" />
    <PackageReference Include="LiteDB.Async" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="MonoMac.Core" />
    <PackageReference Include="ProcessX" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Config.ini">
      <Link>Config.ini</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Config.*.ini">
      <DependentUpon>Config.ini</DependentUpon>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
