name: Build
on:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive
          fetch-depth: 3

      - name: Permissions
        run: chmod +x build.sh

      - name: Pack
        run: ./build.sh --target Pack --no-logo
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Migrations
        uses: actions/upload-artifact@v5
        with:
          name: migrations
          path: |
            output/Scripts/*.sql
          if-no-files-found: warn

      - name: Packages
        uses: actions/upload-artifact@v5
        with:
          name: packages
          path: |
            output/*.nupkg
          if-no-files-found: warn

      - name: Artifacts
        uses: actions/upload-artifact@v5
        with:
          name: artifacts
          path: |
            output/*.zip
          if-no-files-found: warn
