name: Clear

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  remove:
    name: Remove
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      actions: write
    timeout-minutes: 10

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      OWNER: ${{ github.repository_owner }}
      REPO: ${{ github.event.repository.name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Artifacts (>1 day)
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '1 day' # '<number> <unit>', e.g. 5 days, 2 years, 90 seconds, parsed by Moment.js
          # Optional inputs
          # skip-tags: true
          skip-recent: 1

      - name: Workflows (>28 days)
        run: |
          sudo apt-get install jq
          gh run list --limit 200 --json databaseId,createdAt |
          jq -r '[.[] | select((now - (.createdAt | fromdateiso8601)) > (28 * 24 * 60 * 60))] | .[].databaseId' |
          xargs -I ID gh run delete ID

      - name: Workflows (Failed)
        run: |
          sudo apt-get install jq
          gh run list --limit 200 --json databaseId,status,conclusion |
          jq -r '[.[] | select(.status == "completed" and .conclusion == "failure")] | .[].databaseId' |
          xargs -I ID gh run delete ID
